a_tensor_initialization.py

In [15]:
import torch

In [16]:
t1 = torch.Tensor([1, 2, 3], device='cpu')
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu
print(t1.requires_grad)  # >>> False
print(t1.size())  # torch.Size([3])
print(t1.shape)   # torch.Size([3])

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [17]:
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])


In [18]:
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1.shape, a1.ndim)

a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim)

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim)

a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim)

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim)

a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim)

a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim)

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim)


a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim)

a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim)

a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5
torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

텐서를 생성할때 torch.Tensor와 torch.tensor로 생성하는 경우 기본적으로 각각 float32타입과 int64타입으로 생성된다. 이외의 다른부분은 동일하다.
추가로 여러 텐서들이 어떤 구성인지를 확인하고 코드 작성시 에러가 발생할수 있는 상황을 유발하여 확인할 수 있었다.

b_tensor_initialization_copy.py

In [19]:
import torch
import numpy as np

In [20]:
l1 = [1, 2, 3]
t1 = torch.Tensor(l1)

l2 = [1, 2, 3]
t2 = torch.tensor(l2)

l3 = [1, 2, 3]
t3 = torch.as_tensor(l3)

l1[0] = 100
l2[0] = 100
l3[0] = 100

print(t1)
print(t2)
print(t3)

tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])


In [21]:
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


텐서를 생성할때 리스트를 사용할 경우, numpy를 사용할 경우를 각각 알아보는 예제이다. 
이때 numpy를 사용해 생성한 t6을 보면 배열을 그저 복사하는것이 아닌 메모리를 공유하는 방법을 사용하여 만들었으므로 
l6[0] = 100 명령어로 t6의 첫번째 요소가 100으로 바뀐것을 볼 수있다.

c_tensor_initialization_constant_values.py

In [22]:
import torch

In [23]:
t1 = torch.ones(size=(5,))  # or torch.ones(5)
t1_like = torch.ones_like(input=t1)
print(t1)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like)  # >>> tensor([1., 1., 1., 1., 1.])

t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
t2_like = torch.zeros_like(input=t2)
print(t2)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like)  # >>> tensor([0., 0., 0., 0., 0., 0.])

t3 = torch.empty(size=(4,))  # or torch.zeros(4)
t3_like = torch.empty_like(input=t3)
print(t3)  # 추가 주석 빈상태로 생성하기 때문에 메모리에 남아있는 쓰레기 값이 들어감
print(t3_like)  # t1,t2와 달리 t3와 같은 상태로 생성되지 않음

t4 = torch.eye(n=3)
print(t4)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0.])
tensor([2.3694e-38, 2.1250e+00, 0.0000e+00, 0.0000e+00])
tensor([-2.8650e-14,  2.1244e-42,  1.4013e-45,  0.0000e+00])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


이 예제는 1차원텐서를 생성하고 복사하는경우, 그리고 간단히 단위행렬로 텐서를 생성하는 코드이다.
t1, t2의 경우 텐서의 모든 요소를 특정값으로 지정하여 생성하므로 원본과 복사본 모두 특정값을 가지며 정상적으로 생성된다.
t3의 경우 초기화 되지 않은 상태로 생성하기 때문에 메모리에 남아있는값이 들어가 쓰레기값을 가지며 생성된다.
때문에 실행시마다 다른값을 가질수도 있다.
t4는 3x3크기의 단위행렬이 정상적으로 생성되었다.

d_tensor_initialization_random_values.py

In [24]:
import torch

In [25]:
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1)

t2 = torch.rand(size=(1, 3))
print(t2)

t3 = torch.randn(size=(1, 3))
print(t3)

t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4)

t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5)

t6 = torch.arange(5)
print(t6)

tensor([[17, 17]])
tensor([[0.8861, 0.7884, 0.4432]])
tensor([[ 1.3380, -0.4423, -0.1633]])
tensor([[ 9.9795, 10.1763],
        [10.2154, 10.3265],
        [11.5667,  9.8114]])
tensor([0.0000, 2.5000, 5.0000])
tensor([0, 1, 2, 3, 4])


In [26]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

print()

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


텐서를 생성할때 랜덤함수를 사용하는 예제이다.
순서대로 랜덤으로 생성되는 규칙을 특정범위 내 정수, 균일 분포에서 랜덤, 정규 분포에서 랜덤, 정규 분포에서 평균과 표준편차를 적용한 랜덤, 범위를 균일한 간격으로 나누어 생성, 특정 범위내 정수들로 생성이 있었고, t7의 경우 특정 시드를 설정하여 랜덤으로 생성한 텐서를 t8에서 동일한 시드를 사용하여 다시 생성하는것을 보여준다.

e_tensor_type_conversion.py

In [27]:
import torch

In [28]:
a = torch.ones((2, 3))
print(a.dtype)

b = torch.ones((2, 3), dtype=torch.int16)
print(b)

c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)

d = b.to(torch.int32)
print(d)

double_d = torch.ones(10, 2, dtype=torch.double)
short_e = torch.tensor([[1, 2]], dtype=torch.short)

double_d = torch.zeros(10, 2).double()
short_e = torch.ones(10, 2).short()

double_d = torch.zeros(10, 2).to(torch.double)
short_e = torch.ones(10, 2).to(dtype=torch.short)

double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)

print(double_d.dtype)
print(short_e.dtype)

double_f = torch.rand(5, dtype=torch.double)
short_g = double_f.to(torch.short)
print((double_f * short_g).dtype)

torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
torch.float64
torch.int16
torch.float64


다양한 타입의 텐서를 생성하고 데이터 타입을 변환하는 예제이다.
텐서의 데이터 타입을 확인하는 코드, 데이터 타입을 변환시키는 코드를 확인할 수 있고, 중요한 부분은 마지막에 서로 다른 데이터 타입인 두 텐서를 곱한뒤
결과물의 데이터 타입을 확인하는 부분으로 float64와 int16타입의 연산결과 더 정밀한 타입인 float64로 결과값의 데이터 타입이 정해진것을 볼 수있다.

f_tensor_operations.py

In [29]:
import torch

In [30]:
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [31]:
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)
t11 = t3 * t4 #추가코드
print(t11) #추가코드

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[4., 4., 4.],
        [4., 4., 4.]])


In [33]:
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


텐서간의 산술연산을 확인해보는 예제이다.
메서드를 사용하거나 연산자를 사용할 수 있으며 연산시 같은 자리의 값끼리 매칭된다.

g_tensor_operations_mm.py

In [34]:
import torch

In [35]:
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size())

t2 = torch.randn(2, 3)
t3 = torch.randn(3, 2)
t4 = torch.mm(t2, t3)
print(t4, t4.size())

t5 = torch.randn(10, 3, 4)
t6 = torch.randn(10, 4, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor(7) torch.Size([])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])
torch.Size([10, 3, 5])


torch.dot는 내적을 계산하는 메서드이고, torch.mm은 행렬곱을 해주는 메서드이다.
마지막으로 torch.bmm는 배치 행렬곱을 해주는 메서드로 3행4열 과 4행5열이 곱해져 결과가 3행 5열인 것을 확인할 수 있다.

h_tensor_operations_matmul.py

In [36]:
import torch

In [37]:
# vector x vector: dot product
t1 = torch.randn(3)
t2 = torch.randn(3)
print(torch.matmul(t1, t2).size())  # torch.Size([])

# matrix x vector: broadcasted dot
t3 = torch.randn(3, 4)
t4 = torch.randn(4)
print(torch.matmul(t3, t4).size())  # torch.Size([3])

# batched matrix x vector: broadcasted dot
t5 = torch.randn(10, 3, 4)
t6 = torch.randn(4)
print(torch.matmul(t5, t6).size())  # torch.Size([10, 3])

# batched matrix x batched matrix: bmm
t7 = torch.randn(10, 3, 4)
t8 = torch.randn(10, 4, 5)
print(torch.matmul(t7, t8).size())  # torch.Size([10, 3, 5])

# batched matrix x matrix: bmm
t9 = torch.randn(10, 3, 4)
t10 = torch.randn(4, 5)
print(torch.matmul(t9, t10).size())  # torch.Size([10, 3, 5])

torch.Size([])
torch.Size([3])
torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


순서대로 벡터간의 내적, 행렬과 벡터의 곱, 배치행렬과 벡터의 곱, 배치행렬끼리의 곱, 배치행렬과 행렬의 곱의 예제들이다.
이때 배치행렬과 행렬의 곱과 같은 경우 비어있는 차원은 배치행렬을 따라가는것을 알 수 있다.

i_tensor_broadcasting.py

In [38]:
import torch

In [39]:
t1 = torch.tensor([1.0, 2.0, 3.0])
t2 = 2.0
print(t1 * t2) #벡터와 스칼라의 곱셈

tensor([2., 4., 6.])


In [40]:
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])
t4 = torch.tensor([4, 5])
print(t3 - t4) #행렬과 벡터의 뺄셈

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])


In [41]:
t5 = torch.tensor([[1., 2.], [3., 4.]])
print(t5 + 2.0)  # t5.add(2.0)
print(t5 - 2.0)  # t5.sub(2.0)
print(t5 * 2.0)  # t5.mul(2.0)
print(t5 / 2.0)  # t5.div(2.0) #텐서와 스칼라의 사칙연산

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [42]:
def normalize(x): #텐서를 255로 나누는 정규화 함수
  return x / 255


t6 = torch.randn(3, 28, 28)
print(normalize(t6).size()) #정규화를 하더라도 크기는 그대로

torch.Size([3, 28, 28])


In [43]:
t7 = torch.tensor([[1, 2], [0, 3]])  # torch.Size([2, 2])
t8 = torch.tensor([[3, 1]])  # torch.Size([1, 2])
t9 = torch.tensor([[5], [2]])  # torch.Size([2, 1])
t10 = torch.tensor([7])  # torch.Size([1])
print(t7 + t8)   # >>> tensor([[4, 3], [3, 4]])
print(t7 + t9)   # >>> tensor([[6, 7], [2, 5]])
print(t8 + t9)   # >>> tensor([[8, 6], [5, 3]])
print(t7 + t10)  # >>> tensor([[ 8, 9], [ 7, 10]])
#브로드 캐스팅 작은 텐서가 큰 텐서에 맞도록 자동으로 확장됨

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])


In [44]:
t11 = torch.ones(4, 3, 2)
t12 = t11 * torch.rand(3, 2)  # 3rd & 2nd dims identical to t11, dim 0 absent
print(t12.shape)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 3rd dim = 1, 2nd dim is identical to t13
print(t14.shape)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3rd dim is identical to t15, 2nd dim is 1
print(t16.shape)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2nd dim is identical to t17, 3rd and 4th dims are 1
print((t17 + t18).size())
#큰 텐서에 맞추기 때문에 큰 텐서 기준 크기 변동없음

torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])


In [45]:
t19 = torch.empty(5, 1, 4, 1)
t20 = torch.empty(3, 1, 1)
print((t19 + t20).size())  # torch.Size([5, 3, 4, 1]) #큰텐서의 두번째 요소의 크기가 더 작아 1에서 3으로 확장됨

t21 = torch.empty(1)
t22 = torch.empty(3, 1, 7)
print((t21 + t22).size())  # torch.Size([3, 1, 7])

t23 = torch.ones(3, 3, 3)
t24 = torch.ones(3, 1, 3)
print((t23 + t24).size())  # torch.Size([3, 3, 3])

torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])


In [46]:
t27 = torch.ones(4) * 5
print(t27)  # >>> tensor([ 5, 5, 5, 5])

t28 = torch.pow(t27, 2)
print(t28)  # >>> tensor([ 25, 25, 25, 25])

exp = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
a = torch.arange(1., 5.)  # tensor([ 1.,  2.,  3.,  4.])
t29 = torch.pow(a, exp)
print(t29)  # >>> tensor([   1.,    4.,   27.,  256.])
#텐서의 곱셈, 제곱, 지수의 예제이다.

tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


스칼라와 텐서간의 연산, 브로드 캐스팅으로 인한 크기조정 등 다양한 연산의 결과를 보여주는 예제이다.

j_tensor_indexing_slicing.py

In [47]:
import torch

In [48]:
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

print(x[1])  # >>> tensor([5, 6, 7, 8, 9]) #두번째 행 출력
print(x[:, 1])  # >>> tensor([1, 6, 11]) #모든 행의 두번째 열 출력
print(x[1, 2])  # >>> tensor(7) #두번째 행의 세번째 열 출력
print(x[:, -1])  # >>> tensor([4, 9, 14) # 모든행의 마지막 열 출력

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])


In [49]:
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]]) #첫번째 행을 제외한 나머지 행
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]]) #첫번째행 제외, 네번째 열부터 끝까지 출력

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])


In [50]:
y = torch.zeros((6, 6))
y[1:4, 2] = 1 #1행부터 3행, 1열부터 3열까지 1을 할당
print(y)

print(y[1:4, 1:4]) #1행부터 3행, 1열부터 3열까지 출력

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])


In [51]:
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)
print(z[:2]) #첫번째 행과 두번째 행 출력
print(z[1:, 1:3]) #두번째 행부터 끝까지, 두번째 열부터 세번째 열까지 출력
print(z[:, 1:]) #모든 행의 두번째 열부터 끝까지 출력

z[1:, 1:3] = 0 #두번쨰 행부터 끝까지 중 두번째 열과 세번째 열을 0으로 할당
print(z)

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


슬라이싱 방법등으로 행렬의 특정 열, 행을 가져오거나 특정범위를 추출하는 방법을 다루는 예제이다.

k_tensor_reshaping.py

In [52]:
import torch

In [53]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = t1.view(3, 2)  # Shape becomes (3, 2)
t3 = t1.reshape(1, 6)  # Shape becomes (1, 6)
print(t2)
print(t3)

t4 = torch.arange(8).view(2, 4)  # Shape becomes (2, 4)
t5 = torch.arange(6).view(2, 3)  # Shape becomes (2, 3)
print(t4)
print(t5)
# view와 reshape 모두 텐서의 모양을 변경한다(요소는 그대로).

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])


In [54]:
# Original tensor with shape (1, 3, 1)
t6 = torch.tensor([[[1], [2], [3]]])

# Remove all dimensions of size 1
t7 = t6.squeeze()  # Shape becomes (3,)

# Remove dimension at position 0
t8 = t6.squeeze(0)  # Shape becomes (3, 1)
print(t7) #크기가 1인 차원이 삭제됨
print(t8) #첫번째 차원만 삭제됨

tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])


In [55]:
# Original tensor with shape (3,)
t9 = torch.tensor([1, 2, 3])

# Add a new dimension at position 1
t10 = t9.unsqueeze(1)  # Shape becomes (3, 1)
print(t10)

t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)
t12 = t11.unsqueeze(1)  # Shape becomes (2, 1, 3) #차원을 지정한 위치에 가가
print(t12, t12.shape)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])


In [56]:
# Original tensor with shape (2, 3)
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Flatten the tensor
t14 = t13.flatten()  # Shape becomes (6,)

print(t14)

# Original tensor with shape (2, 2, 2)
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])
t16 = torch.flatten(t15)

t17 = torch.flatten(t15, start_dim=1)

print(t16)
print(t17)
#flatten는 모든 요소를 평탄화 하여 1차원으로 만든다.

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [57]:
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# Original tensor with shape (2, 3)
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Permute the dimensions
t20 = torch.permute(t19, dims=(0, 1))  # Shape becomes (2, 3) still
t21 = torch.permute(t19, dims=(1, 0))  # Shape becomes (3, 2)
print(t20)
print(t21)

# Transpose the tensor
t22 = torch.transpose(t19, 0, 1)  # Shape becomes (3, 2)

print(t22)

t23 = torch.t(t19)  # Shape becomes (3, 2)

print(t23)
#permute는 각 위치의 차원을 지정한 번호의 위치하게끔 차원을 이동시킨다
#transpose는 지정한 두 차원의 위치를 바꾼다

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


이 예제는 텐서의 모양을 변경, 차원의 추가, 제거, 평탄화, 위치변경 을 직접 해보는 예제이다.

l_tensor_concat.py

In [58]:
import torch

In [59]:
t1 = torch.zeros([2, 1, 3])
t2 = torch.zeros([2, 3, 3])
t3 = torch.zeros([2, 2, 3])

t4 = torch.cat([t1, t2, t3], dim=1) #텐서들을 특정차원(1)에서 합침
print(t4.shape)#두번째 차원의 값만 증가함

torch.Size([2, 6, 3])


In [60]:
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])
#1차원 텐서의 결합

torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])


In [61]:
t8 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t9 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])

# 2차원 텐서간 병합
t10 = torch.cat((t8, t9), dim=0) #행을 기준으로 결합
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

t11 = torch.cat((t8, t9), dim=1) #열을 기준으로 결합
print(t11.size())  # >>>torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])


In [62]:
t12 = torch.arange(0, 6).reshape(2, 3)  # torch.Size([2, 3])
t13 = torch.arange(6, 12).reshape(2, 3)  # torch.Size([2, 3])
t14 = torch.arange(12, 18).reshape(2, 3)  # torch.Size([2, 3])

t15 = torch.cat((t12, t13, t14), dim=0) #행을 기준으로 결합
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

t16 = torch.cat((t12, t13, t14), dim=1) #열을 기준으로 결합
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])


In [63]:
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # torch.Size([1, 2, 3])
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # torch.Size([1, 2, 3])

t19 = torch.cat((t17, t18), dim=0) #첫번째 차원에서 결합
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

t20 = torch.cat((t17, t18), dim=1) #두번째 차원에서 결합
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

t21 = torch.cat((t17, t18), dim=2) #세번째 차원에서 결합
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])


torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


다양한 차원의 텐서를 각각 결합해보는 예제이다. torch.cat을 사용해서 결합할때 특정 차원만을 기준으로 결합시킬 수 있다.

m_tensor_stacking.py

In [64]:
import torch

In [65]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))

t5 = torch.stack([t1, t2], dim=1)
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))

t7 = torch.stack([t1, t2], dim=2)
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True


In [66]:
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())
# >>> torch.Size([3]) torch.Size([3])

t11 = torch.stack((t9, t10), dim=0)
print(t11.size())  # >>> torch.Size([2,3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))
# >>> True

t13 = torch.stack((t9, t10), dim=1)
print(t13.size())  # >>> torch.Size([3,2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))
# >>> True


torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


텐서끼리 결합시킬때 이전에 사용한 cat 메서드가 아닌 stack메서드를 사용한다
cat과 stack의 차이점으로는 cat은 합치고자 하는 차원을 지정하여 크기가 그차원에서 더한값으로 변경된다.
stack은 새로운 차원을 생성하여 합치기 때문에 두 텐서간의 차원이 일치해야 사용할 수 있다.
위 예제에서 각각의 방법으로 합친 결과가 모두 동일하다는 결과가 나왔다.

n_tensor_vstack_hstack.py

In [67]:
import torch

In [68]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])

t4 = torch.tensor([[1], [2], [3]])
t5 = torch.tensor([[4], [5], [6]])
t6 = torch.vstack((t4, t5))
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])

t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> (2, 2, 3)

t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> (2, 2, 3)

t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> (4, 2, 3)

print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])


In [69]:
t10 = torch.tensor([1, 2, 3])
t11 = torch.tensor([4, 5, 6])
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])

t13 = torch.tensor([[1], [2], [3]])
t14 = torch.tensor([[4], [5], [6]])
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])

t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> (2, 2, 3)

t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> (2, 2, 3)

t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> (2, 4, 3)

print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


텐서를 수직, 수평으로 결합하는 방법을 보여주는 예제이다. vstack이 수직, hstack이 수평으로 결합할 때 사용한다.
때문에 동일한 차원과 크기를 가진 두 텐서간의 결합이 vstack의 경우 첫번째 차원의 크기가 hstack의 경우 두번째 차원의 크기가 증가하는
방향으로 결합된것을 확인할 수 있었다.

숙제후기
파이토치를 처음 사용해보았지만 필요한 여러 연산들에 대하여 출력값까지 예제에 같이 적혀있어서 이해하는데는 큰어려움이 없었습니다.
예제의 양도 난이도에 비하면 많다는 생각이 들지만 지금이 쉬운파트고 앞으로 어려워진다는 것을 생각하면 적절하다는 생각도 들면서 과제의 양이 두렵다는 생각도 들었습니다.
다른 어려움으로는 처음에 주피터 노트북의 사용법을 잘못 이해하여 주피터 노트북이 파일을 읽지 못하거나 과제의 저장이 날라간 경우도 있었습니다. 물론 후기를 작성하는 지금 시점에서는 해결된 문제고 주피터 노트북의 사용법도 천천히 익히고 있습니다. 파이썬을 최근에 많이 다루기도 해서 다른 언어보다는 자신감이 붙어있는 상황이니 이후 강의도 잘 이해하도록 노력하겠습니다.

